### ISSUE TITLE
OOP

### ISSUE THREAD

**Issue by RichardRam87** [NiekSchoone/TopdownZombieShooter#1]
``` c

PistolWeapon.cs Some changes    Sep 29, 2015
PistolWeapon.cs.meta    Lots of stuff   Sep 22, 2015
ShotgunWeapon.cs        
ShotgunWeapon.cs.meta   Lots of stuff   Sep 22, 2015
UziWeapon.cs    Some changes    Sep 29, 2015
UziWeapon.cs.meta 
```

Bestand: https://github.com/NiekSchoone/TopdownZombieShooter/tree/master/Assets/Scripts/WeaponSystem/Weapons

Het gebruik van OOP kan beter in deze classes. Elke class die de weapons class overerft heeft precies dezelfde update loop. In het kader van DRY programmeren had je deze functionaliteit ook in de base-class kunnen definiëren.

**Comment by NiekSchoone** [comment]
Ja, ik had dat gedaan omdat mijn weapon.cs een ScriptableObject is. Daarin kan ik geen fuunctionaliteiten meegeven. Zou ik nog een tussenclass kunnen gebruiken?

**Comment by RichardRam87** [comment]
Een mogelijkheid was een public functie te maken in de ScriptableObject class. Vervolgens roep de deze functie aan zoals je dat gewend bent van normale classes. 
classObj.Function();
