### ISSUE TITLE
Opruimen

### ISSUE THREAD

**Issue by RichardRam87** [NiekSchoone/TopdownZombieShooter#3]
``` c
if(this.gameObject.tag == "Player")
            {

            } 
```

Bestand: https://github.com/NiekSchoone/TopdownZombieShooter/blob/master/Assets/Scripts/Health.cs

Laat lege, oude Classes en/of functies niet staan maar verwijder ze uit je repos als je ze niet meer gaat gebruiken.

**Comment by NiekSchoone** [comment]
Ga ik doen
